[workspace]
members = [
    "cloud-relay",
    "crdt",
    ".",
]

[package]
name = "tlfs"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.44"
bytecheck = "0.6.5"
chacha20poly1305 = { version = "0.9.0", features = ["reduced-round"] }
ed25519-dalek = "1.0.1"
getrandom = "0.2.3"
rkyv = "0.7.18"
sled = { git = "https://github.com/spacejam/sled" }
tlfs-crdt = { version = "0.1.0", path = "crdt" }

[patch.crates-io]
libp2p = { git = "https://github.com/wngr/rust-libp2p", branch = "ow/wasm" }
instant = { git = "https://github.com/wngr/instant", branch = "systemtime" }
