[package]
name = "tlfs-crdt"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.44"
base64 = "0.13.0"
blake3 = "1.0.0"
bytecheck = "0.6.5"
crepe = "0.1.5"
itertools = "0.10.1"
proptest = { version = "1.0.0", optional = true }
rkyv = { version = "0.7.18", features = ["validation"] }
sled = { git = "https://github.com/spacejam/sled" }

[dev-dependencies]
proptest = "1.0.0"
